# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-13 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=256)),
                ('pay', models.SmallIntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('text', models.CharField(max_length=264)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='till_now_app.User'),
        ),
    ]
